### ISSUE TITLE
centre on box not working

### ISSUE THREAD

**Issue by sjpt** [xinaesthete/dat.guiVR#11]
There is already code to centre text in box if no textX specified.
imagebuttongrid around line 149.

This is wrong because w = text.computeWidth(); gives wrong answer where it is.
For simple cases, w = text.computeWidth(); is correct if moved **before** text.constrainBounds(BUTTON_WIDTH - _margin, BUTTON_HEIGHT - _margin);

Not sure exactly how the logic should flow to allow for long text/ wrapped text, etc.

**Comment by xinaesthete** [comment]
This was actually from a local change not even committed to this git repository but copied over to CSynth.
